services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true


##### Website Event Subscriber Kernel
  Austral\WebsiteBundle\EventSubscriber\WebsiteRedirectSubscriber:  "@austral.website.redirect.event_subscriber"
  austral.website.redirect.event_subscriber:
    class:        Austral\WebsiteBundle\EventSubscriber\WebsiteRedirectSubscriber
    arguments:    ["@austral.website.handler"]
    tags:
      - { name: kernel.event_subscriber }

  Austral\WebsiteBundle\EventSubscriber\HttpWebsiteEventSubscriber: "@austral.website.http.event_subscriber"
  austral.website.http.event_subscriber:
    class:        Austral\WebsiteBundle\EventSubscriber\HttpWebsiteEventSubscriber
    arguments:    [ "@service_container", "@austral.website.config", "@austral.http.domains.management", "@austral.tools.debug" ]
    tags:
      - { name: kernel.event_subscriber }

  Austral\WebsiteBundle\EventSubscriber\ConfigVariableFunctionEventSubscriber:  "@austral.website.config.variable.event_subscriber"
  austral.website.config.variable.event_subscriber:
    class:        Austral\WebsiteBundle\EventSubscriber\ConfigVariableFunctionEventSubscriber
    tags:
      - { name: kernel.event_subscriber }


##### Website Listener

  Austral\WebsiteBundle\Listener\DoctrineListener:  "@austral.website.doctrine.listener"
  austral.website.doctrine.listener:
    class:        Austral\WebsiteBundle\Listener\DoctrineListener
    arguments:    ["@austral.website.entity_manager.listener"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }


  Austral\WebsiteBundle\Listener\EntityManagerListener: "@austral.website.entity_manager.listener"
  austral.website.entity_manager.listener:
    class:        Austral\WebsiteBundle\Listener\EntityManagerListener
    arguments:    ["@austral.entity_manager.page"]
    tags:
      - { name: kernel.event_listener, event: "austral.entity_manager.create", method: create }
      - { name: kernel.event_listener, event: "austral.entity_manager.duplicate", method: duplicate }

##### Website Handler
  App\Handler\WebsiteHandler: "@austral.website.handler"
  austral.website.handler:
    class:        App\Handler\WebsiteHandler
    arguments:
      - "@request_stack"
      - "@event_dispatcher"
      - "@security.token_storage"
      - "@austral.tools.debug"
    calls:
      - [ setContainer, [ "@service_container" ] ]
      - [ setMercure, [ "@?austral.notify.mercure" ] ]
      - [ setConfigVariable, [ "@austral.website.config_variable" ] ]

##### Website Template
  Austral\WebsiteBundle\Template\TemplateParameters: "@austral.website.template"
  austral.website.template:
    class:        Austral\WebsiteBundle\Template\TemplateParameters

##### Website Services
  Austral\WebsiteBundle\Services\ConfigVariable: "@austral.website.config_variable"
  austral.website.config_variable:
    class:          Austral\WebsiteBundle\Services\ConfigVariable
    arguments:
      - "@request_stack"
      - "@event_dispatcher"
      - "@austral.http.domains.management"
      - "@doctrine.orm.entity_manager"
      - "@austral.entity_file.link.generator"

  Austral\WebsiteBundle\Services\ConfigReplaceDom: "@austral.website.config_replace_dom"
  austral.website.config_replace_dom:
    class:          Austral\WebsiteBundle\Services\ConfigReplaceDom
    arguments:      ["@austral.website.config_variable", "@austral.http.domains.management", "@austral.seo.url_parameter.management", "@austral.seo.routing"]

##### Entities Manager #####

  ##### Config Entity Manager
  Austral\WebsiteBundle\EntityManager\ConfigEntityManager: "@austral.entity_manager.config"
  austral.entity_manager.config:
    class:          Austral\WebsiteBundle\EntityManager\ConfigEntityManager
    arguments:      [ "@doctrine.orm.entity_manager",  "@event_dispatcher", "%austral.entity.config.class%" ]

  ##### Page Entity Manager
  Austral\WebsiteBundle\EntityManager\PageEntityManager: "@austral.entity_manager.page"
  austral.entity_manager.page:
    class:          Austral\WebsiteBundle\EntityManager\PageEntityManager
    arguments:      [ "@doctrine.orm.entity_manager",  "@event_dispatcher", "%austral.entity.page.class%" ]

  ##### Tracking Entity Manager
  Austral\WebsiteBundle\EntityManager\TrackingEntityManager: "@austral.entity_manager.tracking"
  austral.entity_manager.tracking:
    class:          Austral\WebsiteBundle\EntityManager\TrackingEntityManager
    arguments:      [ "@doctrine.orm.entity_manager",  "@event_dispatcher", "%austral.entity.tracking.class%" ]

##### Parameters #####
  Austral\WebsiteBundle\Configuration\WebsiteConfiguration: "@austral.website.config"
  austral.website.config:
    class:          Austral\WebsiteBundle\Configuration\WebsiteConfiguration
    arguments:      ["%austral_website_config%"]

##### Form Type #####
  Austral\WebsiteBundle\Form\Type\ValueByDomainFormType: "@austral.website.config_value_by_domain.form_type"
  austral.website.config_value_by_domain.form_type:
    class:        Austral\WebsiteBundle\Form\Type\ValueByDomainFormType
    arguments:    [ "@security.authorization_checker" ]
    tags:
      - { name: form.type , alias: austral_config_value_by_domain_form_type }
